version: '3.8'

services:
  clipshare:
    image: ghcr.io/craigjmidwinter/clipshare:latest
    container_name: clipshare-web
    ports:
      - "3000:3000"
    volumes:
      # SINGLE DATA DIRECTORY: All persistent data in one place for easy backup
      # This single directory contains all your data: clips, database, logs, temp files
      - ./data:/app/data
      
      # Optional: Configuration files and environment overrides
      # - ./.env.local:/app/.env.local:ro
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      
      # Database Configuration (optional - uses defaults if not set)
      # - DATABASE_URL=file:./data/db/dev.db
      
      # Authentication (OPTIONAL - generates random secret if not set)
      # - NEXTAUTH_SECRET=your-super-secret-key-at-least-32-characters-long
      # - NEXTAUTH_URL=http://localhost:3000
      
      # File Processing Paths (optional - uses defaults if not set)
      # - CLIPS_DIR=/app/data/processed-files/clips
      # - EXPORT_DIR=/app/data/processed-files/exports
      # - TEMP_DIR=/app/data/temp
      
      # Performance Configuration (optional)
      # - PROCESS_CONCURRENCY=4
      # - MAX_CONCURRENT_JOBS=2
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Note: Plex configuration (server URL, token) is handled through the
# welcome wizard on first startup - no environment variables needed!

volumes:
  # Named volumes (alternative to bind mounts)
  # Uncomment if you prefer Docker-managed volumes
  processed_files:
  temp_files:
  db_data: