services:
  minio:
    image: minio/minio:RELEASE.2024-11-07T00-52-20Z
    container_name: clipshare-minio
    command: server /data --console-address ":9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./.data/minio:/data
  create-buckets:
    image: minio/mc:latest
    container_name: clipshare-minio-init
    depends_on:
      - minio
    entrypoint: ["/bin/sh", "-c"]
    command: >-
      "until (mc alias set local http://minio:9000 minioadmin minioadmin); do echo 'Waiting for MinIO...'; sleep 2; done &&
       until (mc ls local >/dev/null 2>&1); do echo 'Waiting for MinIO API...'; sleep 2; done &&
       mc mb -p local/clipshare || true &&
       mc anonymous set download local/clipshare || true &&
       echo 'Buckets initialized'"

