version: '3.8'

services:
  clipshare:
    image: ghcr.io/craigjmidwinter/clipshare:latest
    container_name: clipshare-web
    ports:
      - "3000:3000"
    volumes:
      # Single data directory - all Clipshare data in one place
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      # Set data directory for application
      - DATA_DIR=/app/data
      # User and Group IDs (defaults to 1000:1000)
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Note: Plex configuration is handled through the welcome wizard on first startup