version: '3.8'

services:
  clipshare:
    image: ghcr.io/craigjmidwinter/clipshare:latest
    container_name: clipshare-web
    ports:
      - "3000:3000"
    volumes:
      # Single data directory - all Clipshare data in one place
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      # Set data directory for application
      - DATA_DIR=/app/data
      # Database URL for Prisma
      - DATABASE_URL=file:/app/data/db/clipshare.db
      # User and Group IDs (defaults to 1001:1001)
      - PUID=1001
      - PGID=1001
      # NextAuth.js secret (default generated, change for production)
      - NEXTAUTH_SECRET=clipshare-default-secret-8f7e6d5c4b3a2918071625344352617
      # Prevent container exit during long operations
      - NODE_OPTIONS=--max-old-space-size=4096
    restart: unless-stopped
    # Increase memory limits for video processing
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

# Note: Plex configuration is handled through the welcome wizard on first startup